### PR TITLE
Change CSS element for responsive toolbar

### PR DESCRIPTION
**Pull request by Guillaume-Bo**
When you have lot of item, it's update can make a new line and adjust to width of window

### CODE REVIEW

**Comment by Guillaume-Bo** [comment]
Example

**Comment by paulhodel** [comment]
We are going to have a problem with that. There are calculations when jexcel on fullscreen. I am going to see how to fix that.

**Comment by Guillaume-Bo** [comment]
hum ok

in my Jexcel with not problem : maybe my code is more complet :

You have my code for "patches" jtoolbar.css

```CSS
.jtoolbar {
    z-index: 10;
}        

.jtoolbar > div {
    display: flex;
    align-items: baseline;
    flex-wrap: wrap;
    justify-content: left;
    width: 100%;
}

.jtoolbar .jtoolbar-item {
    margin: initial;
    flex: 0 0 1px;
}

.jtoolbar .jtoolbar-divisor {
    height: initial;
    align-self: stretch;
    background-color: #CCC;
}

.jtoolbar .jtoolbar-item.jtoolbar-label .material-icons {
    display: inline-block;
    vertical-align: middle;
}

.jtoolbar .jtoolbar-item .jbadge {
    font-size: 11px;
    height: 24px;
    min-width: 48px;
    padding-top: 2px;
    display: table-cell;
    vertical-align: middle;
}
```

**Comment by Guillaume-Bo** [comment]
Ok i understand your problem, size of table of JExcel.

recalculate when resize window ?

**Comment by paulhodel** [comment]
I think due to your last changes this seems no longer relevant. Let me know what do you think.

**Pull request closed without merging**
